spring:
  application:
    name: realtime-gateway
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  cloud:
    function:
      definition: messagePostedEventConsumer
    stream:
      bindings:
        messagePostedEventConsumer-in-0:
          destination: messaging.events
      rabbit:
        bindings:
          messagePostedEventConsumer-in-0:
            consumer:
              exchange-type: topic
              binding-routing-key: messaging.message.posted
server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info
