spring:
  application:
    name: realtime-gateway
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  cloud:
    function:
      definition: messagePostedEventConsumer;relationshipChangeEventConsumer;messageUpdatedEventConsumer
    stream:
      bindings:
        relationshipChangeEventConsumer-in-0:
          destination: user.events
        messagePostedEventConsumer-in-0:
          destination: messaging.events
        messageUpdatedEventConsumer-in-0:
          destination: messaging.events
      rabbit:
        bindings:
          relationshipChangeEventConsumer-in-0:
            consumer:
              binding-routing-key-delimiter: ","
              exchange-type: topic
              binding-routing-key: user.relationship.added,user.relationship.sent
          messageUpdatedEventConsumer-in-0:
            consumer:
              exchange-type: topic
              binding-routing-key: messaging.message.updated
          messagePostedEventConsumer-in-0:
            consumer:
              exchange-type: topic
              binding-routing-key: messaging.message.posted
server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info
