spring:
  application:
    name: users-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: strife
    password: strife
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: strife
    password: strife
  cloud:
    function:
      definition: createProfileConsumer
    stream:
      bindings:
        profileUpdatedEvent-out-0:
          destination: user.events
        createProfileConsumer-in-0:
          destination: account.events
          group: ${spring.application.name}
      rabbit:
        bindings:
          profileUpdatedEvent-out-0:
            producer:
              exchangeType: topic
              routing-key-expression: headers['routingKey']
          createProfileConsumer-in-0:
            consumer:
              exchangeType: topic
              binding-routing-key: auth.account.registered
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET}
