spring:
  application:
    name: messaging-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/messaging_db
    username: strife
    password: strife
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: strife
    password: strife
  cloud:
    function:
      definition: accountCreatedEventConsumer;relationshipChangeEventConsumer
    stream:
      bindings:
        messagePosted-out-0:
          destination: messaging.events
        fileOwnerChanged-out-0:
          destination: messaging.events
        accountCreatedEventConsumer-in-0:
          destination: account.events
          group: ${spring.application.name}
        relationshipChangeEventConsumer-in-0:
          destination: user.events
          group: ${spring.application.name}
      rabbit:
        bindings:
          messagePosted-out-0:
            producer:
              exchange-type: topic
              routing-key-expression: headers['routingKey']
          fileOwnerChanged-out-0:
            producer:
              exchange-type: topic
              routing-key-expression: headers['routingKey']
          accountCreatedEventConsumer-in-0:
            consumer:
              exchange-type: topic
              binding-routing-key: auth.account.registered
          relationshipChangeEventConsumer-in-0:
            consumer:
              exchange-type: topic
              binding-routing-key: user.relationship.*

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
jwt:
  secret: ${JWT_SECRET}
