spring:
  application:
    name: guild-service
  datasource:
    url: jdbc:postgresql://localhost:5432/guild_db
    username: strife
    password: strife
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  rabbitmq:
    host: localhost
    port: 5672
    username: strife
    password: strife

  cloud:
    stream:
      bindings:
        channelCreated-out-0:
          destination: guild.events
      rabbit:
        bindings:
          channelCreated-out-0:
            producer:
              exchange-type: topic
              routing-key-expression: headers['routingKey']

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET}
